-- ELORA Fleet Compliance Portal - Seed Test Data
-- Heidelberg Materials test company with users and sample data
-- Migration: 20250112000003_seed_test_data

-- ============================================================================
-- COMPANY: Heidelberg Materials
-- ============================================================================
INSERT INTO companies (id, name, email_domain, elora_customer_ref, is_active)
VALUES (
    'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
    'Heidelberg Materials',
    'heidelberg.com.au',
    'HM-001',
    true
);

-- ============================================================================
-- CLIENT BRANDING: Heidelberg Materials
-- ============================================================================
INSERT INTO client_branding (
    company_id,
    client_email_domain,
    company_name,
    logo_url,
    primary_color,
    secondary_color
) VALUES (
    'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
    'heidelberg.com.au',
    'Heidelberg Materials',
    NULL, -- Add logo URL if available
    '#003DA5', -- Heidelberg blue
    '#00A3E0'  -- Heidelberg light blue
);

-- ============================================================================
-- USERS: Create test users (requires Supabase Auth setup)
-- Note: In production, users should be created via Supabase Auth signup
-- This is a placeholder showing the expected user_profiles structure
-- ============================================================================

-- Admin user: admin@heidelberg.com.au
-- User ID will be generated by Supabase Auth, this is just a placeholder
DO $$
DECLARE
    admin_user_id uuid := 'hm-admin-uuid-1234-5678-9abc-def012345678'::uuid;
    regular_user_id uuid := 'hm-user-uuid-1234-5678-9abc-def012345679'::uuid;
BEGIN
    -- Insert admin profile (user must be created in Supabase Auth first)
    -- This is commented out as it requires actual auth users to exist
    -- INSERT INTO user_profiles (id, company_id, email, full_name, role, is_active)
    -- VALUES (
    --     admin_user_id,
    --     'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
    --     'admin@heidelberg.com.au',
    --     'Admin User',
    --     'admin',
    --     true
    -- );

    -- Insert regular user profile
    -- INSERT INTO user_profiles (id, company_id, email, full_name, role, is_active)
    -- VALUES (
    --     regular_user_id,
    --     'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
    --     'user@heidelberg.com.au',
    --     'Regular User',
    --     'user',
    --     true
    -- );
END $$;

-- ============================================================================
-- COMPLIANCE TARGETS: Heidelberg Materials
-- ============================================================================
INSERT INTO compliance_targets (
    company_id,
    customer_ref,
    type,
    name,
    target_washes_per_week,
    applies_to
) VALUES
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-001',
        'global',
        'Standard Fleet Compliance',
        2,
        'all'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-001',
        'site',
        'High Traffic Site Target',
        3,
        'site-melb-001'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-001',
        'vehicle',
        'Premium Vehicle Target',
        4,
        'vehicle-premium-001'
    );

-- ============================================================================
-- MAINTENANCE RECORDS: Sample fleet maintenance history
-- ============================================================================
INSERT INTO maintenance_records (
    company_id,
    vehicle_id,
    vehicle_name,
    site_id,
    service_type,
    service_date,
    next_service_date,
    cost,
    description,
    performed_by
) VALUES
    -- Recent services
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-001',
        'Concrete Mixer 001',
        'site-melb-001',
        'oil_change',
        CURRENT_DATE - INTERVAL '5 days',
        CURRENT_DATE + INTERVAL '90 days',
        450.00,
        'Regular oil change and filter replacement',
        'Melbourne Service Center'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-002',
        'Concrete Mixer 002',
        'site-melb-001',
        'tire_rotation',
        CURRENT_DATE - INTERVAL '10 days',
        CURRENT_DATE + INTERVAL '180 days',
        280.00,
        'Tire rotation and alignment',
        'Melbourne Service Center'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-003',
        'Concrete Mixer 003',
        'site-melb-001',
        'inspection',
        CURRENT_DATE - INTERVAL '15 days',
        CURRENT_DATE + INTERVAL '30 days',
        150.00,
        'Quarterly safety inspection',
        'Melbourne Service Center'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-004',
        'Dump Truck 001',
        'site-melb-001',
        'brake_service',
        CURRENT_DATE - INTERVAL '20 days',
        CURRENT_DATE + INTERVAL '120 days',
        850.00,
        'Brake pad replacement and system check',
        'Melbourne Service Center'
    ),
    -- Upcoming service (due soon)
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-005',
        'Dump Truck 002',
        'site-melb-001',
        'oil_change',
        CURRENT_DATE - INTERVAL '85 days',
        CURRENT_DATE + INTERVAL '5 days',
        450.00,
        'Due for oil change',
        'Melbourne Service Center'
    ),
    -- Overdue service
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-006',
        'Concrete Pump 001',
        'site-melb-002',
        'inspection',
        CURRENT_DATE - INTERVAL '125 days',
        CURRENT_DATE - INTERVAL '5 days',
        150.00,
        'OVERDUE: Quarterly inspection',
        'Sydney Service Center'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-007',
        'Concrete Pump 002',
        'site-melb-002',
        'oil_change',
        CURRENT_DATE - INTERVAL '100 days',
        CURRENT_DATE - INTERVAL '10 days',
        450.00,
        'OVERDUE: Oil change required',
        'Sydney Service Center'
    ),
    -- More historical records
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-008',
        'Agitator Truck 001',
        'site-syd-001',
        'transmission_service',
        CURRENT_DATE - INTERVAL '30 days',
        CURRENT_DATE + INTERVAL '330 days',
        1200.00,
        'Transmission fluid change and inspection',
        'Sydney Service Center'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-009',
        'Agitator Truck 002',
        'site-syd-001',
        'tire_replacement',
        CURRENT_DATE - INTERVAL '45 days',
        NULL,
        2400.00,
        'Full tire replacement - all 6 tires',
        'Sydney Service Center'
    ),
    (
        'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid,
        'HM-TRUCK-010',
        'Transit Mixer 001',
        'site-syd-002',
        'hydraulic_service',
        CURRENT_DATE - INTERVAL '60 days',
        CURRENT_DATE + INTERVAL '120 days',
        680.00,
        'Hydraulic system maintenance and leak check',
        'Sydney Service Center'
    );

-- ============================================================================
-- SAMPLE DATA SUMMARY
-- ============================================================================
-- Companies: 1 (Heidelberg Materials)
-- Client Branding: 1
-- Compliance Targets: 3 (global, site-specific, vehicle-specific)
-- Maintenance Records: 10 (mix of recent, upcoming, and overdue)
--
-- Note: User profiles require Supabase Auth users to exist first
-- Create users via Supabase dashboard or Auth API, then add profiles
--
-- To test notifications:
-- 1. Create auth users for admin@heidelberg.com.au and user@heidelberg.com.au
-- 2. Add their profiles to user_profiles table
-- 3. Run the checkNotifications function
-- ============================================================================

-- ============================================================================
-- HELPER: Create user profile after auth signup
-- This function can be called after creating a user via Supabase Auth
-- ============================================================================
CREATE OR REPLACE FUNCTION public.create_user_profile(
    user_id uuid,
    user_email text,
    user_full_name text DEFAULT NULL,
    user_role text DEFAULT 'user'
)
RETURNS void AS $$
DECLARE
    user_company_id uuid;
    email_domain text;
BEGIN
    -- Extract email domain
    email_domain := split_part(user_email, '@', 2);

    -- Find company by email domain
    SELECT id INTO user_company_id
    FROM companies
    WHERE email_domain = create_user_profile.email_domain
    LIMIT 1;

    -- If no company found, use Heidelberg Materials as default for testing
    IF user_company_id IS NULL THEN
        user_company_id := 'hm-001-uuid-4a8b-9c3d-e2f1a5b6c7d8'::uuid;
    END IF;

    -- Insert user profile
    INSERT INTO user_profiles (id, company_id, email, full_name, role, is_active)
    VALUES (user_id, user_company_id, user_email, user_full_name, user_role, true)
    ON CONFLICT (id) DO NOTHING;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.create_user_profile IS 'Helper function to create user profile after Supabase Auth signup';

-- ============================================================================
-- VERIFICATION QUERIES (for testing)
-- ============================================================================
-- SELECT * FROM companies;
-- SELECT * FROM compliance_targets;
-- SELECT * FROM maintenance_records ORDER BY service_date DESC;
-- SELECT * FROM user_profiles;
-- ============================================================================
