-- ============================================================================
-- Marketplace · Checkout enrichment (Phase: CQVS-style checkout migration)
--
-- Adds buyer-supplied fields that the new inline (Payment Element + 4-step)
-- checkout captures alongside the cart:
--   - po_number          buyer's internal PO reference, free text
--   - invoice_email      override of companies.marketplace_invoice_email
--   - po_attachments     JSONB array of {path, name, size, type} — replaces
--                        single po_pdf_path with multi-file support (PDF,
--                        DOC/DOCX, XLS/XLSX, JPG/PNG/WEBP). po_pdf_path stays
--                        for back-compat — code keeps writing the first
--                        attachment's path into it so existing readers (Xero,
--                        email templates) keep working.
--   - forklift_available a hard-flag captured in the delivery step so the
--                        freight engine + dispatch team know if a tailgate
--                        truck is needed.
-- ============================================================================

ALTER TABLE marketplace_orders
  ADD COLUMN IF NOT EXISTS po_number          TEXT,
  ADD COLUMN IF NOT EXISTS invoice_email      TEXT,
  ADD COLUMN IF NOT EXISTS po_attachments     JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS forklift_available BOOLEAN;

COMMENT ON COLUMN marketplace_orders.po_number IS
  'Buyer-supplied PO reference (free text). Distinct from xero_po_number which is generated by Xero.';

COMMENT ON COLUMN marketplace_orders.invoice_email IS
  'Per-order override of the company''s marketplace_invoice_email. Used as the To: for the invoice email when set.';

COMMENT ON COLUMN marketplace_orders.po_attachments IS
  'JSONB array of buyer-uploaded PO attachments: [{path, name, size, type}]. po_pdf_path keeps the first entry for back-compat with existing Xero attachment readers.';

COMMENT ON COLUMN marketplace_orders.forklift_available IS
  'Buyer-declared forklift availability at the delivery site. NULL = unknown (legacy orders). FALSE means a tailgate truck is required.';

-- ============================================================================
-- Widen marketplace-po-uploads bucket to accept DOC/DOCX/XLS/XLSX/JPEG/PNG/WEBP
-- alongside PDF, to match the new multi-file upload control on checkout.
-- (CQVS Chem Connect supports the same set.)
-- ============================================================================
UPDATE storage.buckets
SET allowed_mime_types = ARRAY[
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/webp'
]
WHERE id = 'marketplace-po-uploads';
